# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :jekyll_plugins do
  gem 'asciidoctor', "~> 1.5"
  gem 'asciidoctor-interdoc-reftext', '~> 0.5'
  gem 'asciidoctor-dtu-enote', :path => '../translator'
end

gem "pry", "~> 0.12.2"

gem "awesome_print", "~> 1.8"
