  # frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "asciidoctor", "~> 1.5"

gem "asciidoctor-question", path: "./asciidoctor-question"

gem "pry", "~> 0.12.2"

gem "awesome_print", "~> 1.8"

gem "pry-coolline", "~> 0.2.5"
